sculpin_content_types:
    elephpants:
        taxonomies:
            - categories
            - tags
    others:
        taxonomies:
            - categories
            - tags
    posts:
        enabled: false
    sections:
services:
    elephpant_twig_extension:
        class: ElephpantTwigExtension
        tags:
            - { name: twig.extension }
